modified method simple_accuracy(), before: it's (preds == labels).mean() This will cause an exception[AttributeError: 'bool' object has no attribute 'mean'], then after update: change to accuracy_score(labels,preds), use this method accuracy_score() in package sklearn.metrics