Fix AttributeError: 'MMBTConfig' object has no attribute 'use_return_dict'
Attributes are copied from transformers.PreTrainedConfig.__dict__ which does not contain object properties.
use_return_dict is an object property that's not in object.__dict__