example code missing `encode`
following example, and realized by running 
```
In [27]:     encoding = tokenizer(text_batch, return_tensors='pt', padding=True, truncation=True)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-27-c8731cd264f2> in <module>
----> 1 encoding = tokenizer(text_batch, return_tensors='pt', padding=True, truncation=True)

TypeError: 'BertTokenizer' object is not callable
```