Update generation_configuration_bark.py
Fix validation error:
ValueError: `do_sample` is set to `False`. However, temperature is set to 0.5 -- this flag is only used in sample-based generation modes. Set `do_sample=True` or unset temperature to continue.