[setup] require torch>=1.4
I re-run the test suite on lower torch versions:

* torch-1.2 and below is definitely a no go - a gazillion of errors in the test suite.

* torch-1.3+ is mostly OK, but:
```
FAILED tests/test_modeling_bart.py::BartHeadTests::test_generate_fp16 - RuntimeError: "argmax_cuda" not implemented for 'Half'
FAILED tests/test_modeling_funnel.py::FunnelModelIntegrationTest::test_inference_tiny_model - OSError: Unable to load weights from pytorch checkpoi...
FAILED tests/test_modeling_gpt2.py::GPT2ModelTest::test_model_outputs_equivalence - RuntimeError: Expected object of scalar type Float but got scal...
FAILED tests/test_modeling_lxmert.py::LxmertModelTest::test_lxmert_pretraining - RuntimeError: Expected object of scalar type Float but got scalar ...
FAILED tests/test_modeling_openai.py::OpenAIGPTModelTest::test_model_outputs_equivalence - RuntimeError: Expected object of scalar type Float but g...
FAILED tests/test_modeling_reformer.py::ReformerLocalAttnModelTest::test_reformer_model_fp16_generate - RuntimeError: "argmax_cuda" not implemented...
FAILED tests/test_modeling_reformer.py::ReformerLSHAttnModelTest::test_reformer_model_fp16_forward - RuntimeError: "argmax_cuda" not implemented fo...
FAILED tests/test_modeling_reformer.py::ReformerLSHAttnModelTest::test_reformer_model_fp16_generate - RuntimeError: "argmax_cuda" not implemented f...
```
which could be fixed in core if desired, but it won't pass as is right now.

* torch-1.4 - has mostly serialization issues (files saved with new pytorch can't be read by the old one) 

Hence changing to `torch>=1.4`

@sgugger, @LysandreJik