Catch ConfigError when attempting to set num_parameters in WANDB
The current version of the code catches AttributeError when
attempting to set the model's number of parameters in the
Weights & Biases config.

ConfigError is another exception that needs catching in the case
when the current number of model parameters differs from that
of the config. This happens, for example, on resuming from checkpoints if
extra layers have been added.

Example error message:

```
wandb.sdk.lib.config_util.ConfigError: Attempted to change value of key "model/num_parameters" from 0 to 700416
```

Since the current code already includes support for ignoring
AttributeError, it feels safe to add this extra catch.