Bugfix for encoding error during GPT2Tokenizer.from_pretrained('local/path/to/mode')
BUGFIX: Loading GPT2-tokenizer from local path with
GPT2Tokenizer.from_pretrained(pretrained_model_name_or_path='local/path/to/model')
returns following error due to encoding error for json.load():
Traceback (most recent call last):
  File "/opt/pycharm-2019.1.3/helpers/pydev/pydevd.py", line 1758, in <module>
    main()
  File "/opt/pycharm-2019.1.3/helpers/pydev/pydevd.py", line 1752, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/opt/pycharm-2019.1.3/helpers/pydev/pydevd.py", line 1147, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/opt/pycharm-2019.1.3/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/developer/AmI/transfer-learning-conv-ai/pytorch_transformer_evaluation.py", line 24, in <module>
    cache_dir=None)
  File "/home/developer/AmI/pytorch-transformers/pytorch_transformers/tokenization_utils.py", line 151, in from_pretrained
    return cls._from_pretrained(*inputs, **kwargs)
  File "/home/developer/AmI/pytorch-transformers/pytorch_transformers/tokenization_utils.py", line 240, in _from_pretrained
    tokenizer = cls(*inputs, **kwargs)
  File "/home/developer/AmI/pytorch-transformers/pytorch_transformers/tokenization_gpt2.py", line 110, in __init__
    self.encoder = json.load(open(vocab_file))
  File "/conda/envs/rapids/lib/python3.6/json/__init__.py", line 296, in load
    return loads(fp.read(),
  File "/conda/envs/rapids/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 840: ordinal not in range(128)